version: "2"

services:
  guacamole-client:
    extends:
      file: ./docker-compose.yml
      service: guacamole-client
    container_name: guacamole-client

  guacd:
    extends:
      file: ./docker-compose.yml
      service: guacd
    container_name: guacd

  ubuntu-qemu:
    extends:
      file: ./docker-compose.yml
      service: ubuntu-qemu
    container_name: ubuntu-qemu

  backend:
    extends:
      file: ./docker-compose.yml
      service: backend
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    image: human-apps/backend:dev
    volumes:
      - ./backend:/opt
    ports:
      - 5858:5858
      - 8081:8081
    container_name: backend

  frontend:
    extends:
      file: ./docker-compose.yml
      service: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    image: human-apps/frontend:dev
    volumes:
      - ./frontend:/opt
    ports:
      - 49152:49152
    container_name: frontend

networks:
  human-apps:
    driver: bridge
