FROM human-apps/backend
MAINTAINER Olivier Berthonneau <berthonneau.olivier@gmail.com>

RUN npm install nodemon node-inspector -g

EXPOSE 5858
EXPOSE 8081

CMD npm install ; (node-inspector --web-port=8081 &) ; nodemon --exec 'node --debug' index.js
