version: "2"

services:
  guacamole-client:
    build:
      context: ./guacamole-client
    image: human-apps/guacamole-client
    ports:
      - 8080:8080
    network_mode: "host"
    restart: always

  guacd:
    image: glyptodon/guacd
    network_mode: "host"
    restart: always

  ubuntu-qemu:
    build:
      context: ./ubuntu-qemu
    image: human-apps/ubuntu-qemu
    volumes:
      - ./ubuntu-qemu/ubuntu.qcow2:/ubuntu.qcow2
    devices:
      - /dev/kvm
    restart: always
