version: "2"

services:
  guacamole-client:
    build:
      context: ./guacamole-client
    image: human-apps/guacamole-client
    volumes:
       - ./guacamole-client/guacamole.dev.properties:/etc/guacamole/guacamole.properties:ro
       - ./guacamole-client/noauth-config.dev.xml:/etc/guacamole/noauth-config.xml:ro
    ports:
      - 8080:8080
    network_mode: host
    container_name: guacamole-client

  guacd:
    image: glyptodon/guacd
    network_mode: host
    container_name: guacd

  ubuntu-qemu:
    build:
      context: ./ubuntu-qemu
    image: human-apps/ubuntu-qemu
    volumes:
      - ./ubuntu-qemu/images:/images
    devices:
      - /dev/kvm
    network_mode: host
    container_name: ubuntu-qemu

  backend:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    image: human-apps/backend:dev
    volumes:
      - ./:/opt
    ports:
      - 3000:3000
      - 5858:5858
      - 8081:8081
    network_mode: host
    container_name: backend
    environment:
      - UBUNTU_HOST=localhost
      - GUACAMOLE_HOST=localhost

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    image: human-apps/frontend:dev
    volumes:
      - ./frontend:/opt
    ports:
      - 49152:49152
      - 4200:4200
    container_name: frontend
    network_mode: host

  proxy:
    build: ./nginx
    ports:
      - 80:80
    image: human-apps/proxy
    volumes:
       - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    container_name: "proxy"
    network_mode: host
