version: "2"

services:
  guacamole-client:
    build:
      context: ./guacamole-client
    image: human-apps/guacamole-client
    ports:
      - 8080:8080
    networks:
      - human-apps
    restart: always

  guacd:
    image: glyptodon/guacd
    networks:
      - human-apps
    restart: always

  ubuntu-qemu:
    build:
      context: ./ubuntu-qemu
    image: human-apps/ubuntu-qemu
    volumes:
      - ./ubuntu-qemu/ubuntu.qcow2:/ubuntu.qcow2
    devices:
      - /dev/kvm
    networks:
      - human-apps
    restart: always

  backend:
    build:
      context: ./backend
    image: human-apps/backend
    volumes_from:
      - frontend
    networks:
      - human-apps
    restart: always

  frontend:
    build:
      context: ./frontend
    image: human-apps/frontend
    networks:
      - human-apps
    restart: always

  proxy:
    build: ./nginx
    ports:
      - 80:80
    image: human-apps/proxy
    depends_on:
      - backend
    restart: always
    container_name: "proxy"
    networks:
      - human-apps

networks:
  human-apps:
    driver: bridge
